-
  name: Sonarqube install on EC2
  hosts: localhost
  vars:
    password: sonar1234
    base: /opt/sonarqube/sonarqube-9.5.0.56709
    username: sonar
  tasks:
    - name: Install JAVA 
      command: "{{item}}"
      with_items: 
        - amazon-linux-extras install java-openjdk11 -y
        - java -version
      become: yes
    
    - name: Install unzip
      yum: 
        name: unzip
        state: present
      become: yes

    - name: Setup linux goup
      group:
        name: sonar
        state: present
      become: yes
    
    - name: Setup linux user
      user:
        name: sonar
        group: sonar
        password: "{{ password | password_hash('sha512') }}"
      become: yes

    - name: Creates directory /opt/sonarqube
      file:
        path: /opt/sonarqube
        mode: '775'
        group: sonar
        owner: sonar
        state: directory
      become: yes

    - name: Sonar setup management
      unarchive: 
        src: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.5.0.56709.zip
        dest: /opt/sonarqube
        owner: sonar
        mode: '775'
        remote_src: yes
      become: yes


    - name: Run as user sonar.sh modify
      lineinfile:
        dest: "{{base}}/bin/linux-x86-64/sonar.sh"
        regexp: "#RUN_AS_USER="
        line: RUN_AS_USER=sonar
        state: present
      become: yes

    - name: Modify sonar.jdbc.username sonar.properties file
      lineinfile:
        dest: "{{base}}/conf/sonar.properties"
        regexp: "#sonar.jdbc.username="
        line: sonar.jdbc.username={{username}}
        state: present
      become: yes
    
    - name: Modify sonar.jdbc.password sonar.properties file
      lineinfile:
        dest: "{{base}}/conf/sonar.properties"
        regexp: "#sonar.jdbc.password="
        line: sonar.jdbc.password={{password}}
        state: present
      become: yes
    

    - name: Modify sonar.jdbc.url sonar.properties file 
      lineinfile:
        dest: "{{base}}/conf/sonar.properties"
        regexp: "#sonar.jdbc.url=jdbc:postgresql://localhost/sonarqube?currentSchema=my_schema"
        line: "sonar.jdbc.url=jdbc:postgresql://{{lookup('ansible.builtin.env', 'RDS')}}/db_sonarqube"
        state: present
      become: yes

    - name: Modify vm.max_map_count on /etc/sysctl.conf
      lineinfile:
        dest: "/etc/sysctl.conf"
        line: vm.max_map_count=524288
        state: present
      become: yes

    - name: Modify fs.file-max on /etc/sysctl.conf
      lineinfile:
        dest: "/etc/sysctl.conf"
        line: fs.file-max=131072
        state: present
      become: yes

    - name: Update sysctl 
      command: sysctl -p 
      become: yes

    - name: Run Sonarqube sonar.sh
      command: "{{item}}"
      with_items:
        - cd {{base}}/bin/linux-x86-64
        - sh sonar.sh start

  